hugoblox:
  schema: "2.0"
  identity:
    name: Andrée Barnier
    type: person
    tagline: PhD in applied mathematics
    description: |-
      I am PhD student in mathematics in INRAE, Jouy-en-josas working under the supervision of Estelle Kuhn et Patrick Hoscheit.
      I am intrested in probability theory
  theme:
    mode: system
    pack: dracula
    colors:
      primary: emerald
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
